#!/bin/bash

SNS License

Copyright (c) 2023 minjuno, hanjungwoo7


이 소프트웨어와 관련된 문서 파일(“Shell”)의 사본을 얻는 모든 사용자에게 다음의 권한을 무상으로 부여합니다.
이 소프트웨어의 사본을 무제한으로 사용, 복제, 수정, 병합, 게시, 배포할 수 있는 권한을 무상으로 부여합니다.


minjuno <ijunho0924@naver.com>
